swagger: '2.0'
info:
  description: Corporate Name Search
  version: 1.0.0
  title: Corporate Name Search
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/search/v1
tags:
  - name: search
    description: Calls regarding name search
schemes:
  - http
paths:
  /search:
    get:
      tags:
        - search
      summary: Runs a search on the string against the existing data
      description: Runs a search on the string against the existing data
      operationId: search
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: q
          description: The value to search for
          required: true
          type: string
        - in: query
          name: limit
          default: 20
          description: The limit of the search
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: JSON array of search hit results
          schema:
            $ref: '#/definitions/searchSuccess'
        '405':
          description: Unexpected error
          schema:
            $ref: '#/definitions/errors'
definitions:
  errors:
    properties:
      error:
        type: string
      errorCode:
        type: integer
        format: int32
  searchSuccess:
    properties:
      hits:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            label:
              type: string
            value:
              type: string
